In [23]:
from google.colab import drive
drive.mount('/content/drive')

# Notice the quotes around the Drive path to handle the spaces!
!cp "/content/drive/MyDrive/DLCVProjectCode/DLCV_Project_Code.zip" /content/
!unzip -q -o /content/DLCV_Project_Code.zip -d /content/workspace
%cd /content/workspace

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/workspace


In [26]:
import json
import os

# ---> PASTE YOUR KAGGLE INFO HERE <---
kaggle_creds = {
    "username": "srinathkaggle",
    "key": "KGAT_34c34e54f710de7fa51d6b514f81b9c8"
}

# 1. Setup the Kaggle config folder in the root directory
os.makedirs('/root/.kaggle', exist_ok=True)

# 2. Write the credentials to the json file
with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump(kaggle_creds, f)

# 3. Set the required permissions (Kaggle CLI will fail without this)
os.chmod('/root/.kaggle/kaggle.json', 0o600)

# 4. Download and unzip using the exact name from your URL
!mkdir -p data
!kaggle datasets download -d masoudnickparvar/brain-tumor-mri-dataset -p data
!cd data && unzip -q -o brain-tumor-mri-dataset.zip && cd ..

# 5. Install dependencies
!pip install -r requirements.txt

Dataset URL: https://www.kaggle.com/datasets/masoudnickparvar/brain-tumor-mri-dataset
License(s): Attribution 4.0 International (CC BY 4.0)
brain-tumor-mri-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)


In [25]:
%cd /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes

/content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes


In [27]:
!echo "=== STARTING EFFICIENTNET BASELINE: $(date) ==="
!python train.py --model efficientnet_b0 --epochs 30 --num_workers 0 --batch_size 64

!echo "=== STARTING EFFICIENTNET SAM: $(date) ==="
!python train.py --model efficientnet_b0 --use_sam --rho 0.05 --epochs 30 --num_workers 0 --batch_size 64

!echo "=== STARTING RESNET-50: $(date) ==="
!python train.py --model resnet50 --epochs 30 --num_workers 0 --batch_size 64

!echo "=== ALL TRAINING FINISHED: $(date) ==="

=== STARTING EFFICIENTNET BASELINE: Wed Apr 29 08:45:33 PM UTC 2026 ===
Using device: cuda
Epoch 1/30  train_loss=0.5048  val_macro_f1=0.8975  val_acc=0.8981  val_auroc=0.9764
  -> saved /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes/outputs/checkpoints/best_efficientnet_b0_baseline.pt
Epoch 2/30  train_loss=0.2290  val_macro_f1=0.9260  val_acc=0.9259  val_auroc=0.9912
  -> saved /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes/outputs/checkpoints/best_efficientnet_b0_baseline.pt
Epoch 3/30  train_loss=0.1698  val_macro_f1=0.9553  val_acc=0.9556  val_auroc=0.9962
  -> saved /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes/outputs/checkpoints/best_efficientnet_b0_baseline.pt
Epoch 4/30  train_loss=0.1337  val_macro_f1=0.9703  val_acc=0.9704  val_auroc=0.9982
  -> saved /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes/outputs/checkp

In [32]:
!pwd

/content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes


In [30]:
# Saving back to the new folder with quotes
!cp -r /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes/outputs/checkpoints "/content/drive/MyDrive/DLCVProjectCode/"

In [33]:
# 1. Evaluate EfficientNet Baseline
!python eval.py --checkpoint outputs/checkpoints/best_efficientnet_b0_baseline.pt --output_dir outputs/results/baseline

# 2. Evaluate EfficientNet SAM
!python eval.py --checkpoint outputs/checkpoints/best_efficientnet_b0_sam.pt --output_dir outputs/results/sam

# 3. Evaluate ResNet-50
!python eval.py --checkpoint outputs/checkpoints/best_resnet50_baseline.pt --output_dir outputs/results/resnet50

Using device: cuda
Saved outputs/results/baseline/metrics_best_efficientnet_b0_baseline.json
Test results:
  Accuracy:       0.9898
  Macro-F1:       0.9898
  Macro-Precision:0.9898
  Macro-Recall:   0.9898
  AUROC:          0.9978
Confusion matrix:
[[269   1   0   0]
 [  2 265   2   1]
 [  2   0 267   1]
 [  0   2   0 268]]
Saved outputs/results/baseline/metrics_best_efficientnet_b0_baseline.md
Using device: cuda
Saved outputs/results/sam/metrics_best_efficientnet_b0_sam.json
Test results:
  Accuracy:       0.9880
  Macro-F1:       0.9879
  Macro-Precision:0.9880
  Macro-Recall:   0.9880
  AUROC:          0.9993
Confusion matrix:
[[268   2   0   0]
 [  5 262   1   2]
 [  1   0 268   1]
 [  0   1   0 269]]
Saved outputs/results/sam/metrics_best_efficientnet_b0_sam.md
Using device: cuda
Saved outputs/results/resnet50/metrics_best_resnet50_baseline.json
Test results:
  Accuracy:       0.9880
  Macro-F1:       0.9880
  Macro-Precision:0.9880
  Macro-Recall:   0.9880
  AUROC:          0.99

In [34]:
!ls -R /content/workspace

Streaming output truncated to the last 5000 lines.
attr.h		    embed.h		  pybind11.h
buffer_info.h	    eval.h		  pytypes.h
cast.h		    functional.h	  stl
chrono.h	    gil.h		  stl_bind.h
common.h	    gil_safe_call_once.h  stl.h
complex.h	    gil_simple.h	  subinterpreter.h
conduit		    iostream.h		  trampoline_self_life_support.h
critical_section.h  native_enum.h	  type_caster_pyobject_ptr.h
detail		    numpy.h		  typing.h
eigen		    operators.h		  warnings.h
eigen.h		    options.h

/content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification/venv/lib/python3.13/site-packages/torch/include/pybind11/conduit:
pybind11_conduit_v1.h  pybind11_platform_abi_id.h  wrap_include_python_h.h

/content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification/venv/lib/python3.13/site-packages/torch/include/pybind11/detail:
class.h				    internals.h
common.h			    native_enum_data.h
cpp_conduit.h			    pybind11_namespace_macros.h
descr.h				    struct_smart_holder.h
dynamic_raw_ptr_c

In [35]:
!pwd

/content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes


In [36]:
import os
import sys

# Add the current directory to the path so it can find the explainability module
os.environ['PYTHONPATH'] = "/content/workspace:" + os.environ.get('PYTHONPATH', '')

# Now run the explainability script
!python explain.py --checkpoint outputs/checkpoints/best_efficientnet_b0_sam.pt --output_dir outputs/results/explainability

Using device: cuda
Explain:   0% 0/8 [00:00<?, ?it/s]Saved outputs/results/explainability/explainability/explain_00_true_glioma_pred_glioma.png
Explain:  12% 1/8 [00:02<00:18,  2.70s/it]Saved outputs/results/explainability/explainability/explain_01_true_glioma_pred_glioma.png
Explain:  25% 2/8 [00:05<00:16,  2.79s/it]Saved outputs/results/explainability/explainability/explain_02_true_meningioma_pred_meningioma.png
Explain:  38% 3/8 [00:08<00:14,  2.95s/it]Saved outputs/results/explainability/explainability/explain_03_true_meningioma_pred_meningioma.png
Explain:  50% 4/8 [00:10<00:10,  2.67s/it]Saved outputs/results/explainability/explainability/explain_04_true_notumor_pred_notumor.png
Explain:  62% 5/8 [00:13<00:07,  2.49s/it]Saved outputs/results/explainability/explainability/explain_05_true_notumor_pred_notumor.png
Explain:  75% 6/8 [00:15<00:04,  2.38s/it]Saved outputs/results/explainability/explainability/explain_06_true_pituitary_pred_pituitary.png
Explain:  88% 7/8 [00:17<00:02, 

In [38]:
# Sync both checkpoints and result visualizations
!cp -r /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes/outputs/checkpoints "/content/drive/MyDrive/DLCVProjectCode/"
!cp -r /content/workspace/NeuroScan---Explainable-Brain-Tumour-Classification-required-changes/outputs/results "/content/drive/MyDrive/DLCVProjectCode/"
!echo "=== ALL FILES SECURED TO DRIVE: $(date) ==="

=== ALL FILES SECURED TO DRIVE: Wed Apr 29 10:40:30 PM UTC 2026 ===
